# cat /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml

# gatewayAPI:
#   enabled: true
# hubble:
#   enabled: true
#   relay:
#     enabled: true
#   ui:
#     enabled: true
# encryption:
#   enabled: true
#   type: wireguard
#   nodeEncryption: true

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
operator:
  replicas: 1
spec:
  valuesContent: |-
    image:
      tag: v1.18.0
    kubeProxyReplacement: true
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 443
    operator:
      replicas: 1
    gatewayAPI:
      enabled: true
