# # cilium/kustomization.yaml
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# resources:
#   - announce.yaml
#   - ip-pool.yaml

# helmCharts:
#   - name: cilium
#     repo: https://helm.cilium.io
#     version: 1.17.6
#     releaseName: "cilium"
#     includeCRDs: true
#     namespace: kube-system
#     valuesFile: values.yaml

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      tag: v1.17.6
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
    kubeProxyReplacement: true
    gatewayAPI:
      enabled: true
      hostNetwork:
        enabled: true
      enableAlpn: true
      gatewayClass:
        create: true
    envoy:
      securityContext:
        capabilities:
          keepCapNetBindService: true
          envoy:
            - NET_ADMIN
            - PERFMON
            - BPF
    rollOutCiliumPods: true
    operator:
      rollOutPods: true

    k8sClientRateLimit:
      qps: 100
      burst: 200

    l2announcements:
      enabled: true