apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    releaseName: my-cilium
    version: 1.18.0

# configMapGenerator:
#   - name: cilium
#     files:
#       - cilium.properties
