apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: actualbudget
    repo: https://community-charts.github.io/helm-charts
    namespace: actualbudget
    version: 1.8.1
    releaseName: my-actualbudget