apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: argocd-gateway
  namespace: argocd
  annotations:
    cert-manager.io/issuer: ca-issuer
spec:
  gatewayClassName: cilium
  listeners:
  - hostname: argocd.localhost
    name: argocd-example-com-http
    port: 80
    protocol: HTTP
  - hostname: argocd.localhost
    name: argocd-example-com-https
    port: 443
    protocol: HTTPS
  tls:
    certificateRefs:
    - kind: Secret
      name: argocd-server-tls
