apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    encryption:
      enabled: true
      type: wireguard
    kubeProxyReplacement: true
    k8sServiceHost: "localhost"
    k8sServicePort: "6443"
    encryption:
      enabled: true
      type: wireguard
    externalIPs:
      enabled: true
    kubeProxyReplacement: true
    operator:
      replicas: 1
    gatewayAPI:
      enabled: true
      gatewayClass:
        create: true
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    l2announcements:
      enabled: true
    k8sClientRateLimit:
      burst: 40 # Important value when many services run on a Kubernetes cluster. Check out the documentation https://docs.cilium.io/en/v1.17/network/l2-announcements/#sizing-client-rate-limit
      qps: 20 # Important value when many services run on a Kubernetes cluster. Check out the documentation https://docs.cilium.io/en/v1.17/network/l2-announcements/#sizing-client-rate-limit
    cluster:
      name: on-site
      id: 001
