apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    encryption:
      enabled: true
      type: wireguard
    k8sServiceHost: "localhost"
    k8sServicePort: "6443"
    kubeProxyReplacement: true
    operator:
      replicas: 1
    gatewayAPI:
      enabled: true
      gatewayClass:
        create: "true"
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true