apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    encryption:
      enabled: true
      type: wireguard
    kubeProxyReplacement: true
    operator:
      replicas: 1
    gatewayAPI:
      enabled: true
      gatewayClass:
        create: "true"
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    cluster:
      name: on-site
      id: 001