apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    encryption:
      enabled: true
      type: wireguard
    kubeProxyReplacement: true
    k8sServiceHost: "localhost"
    k8sServicePort: "6443"
        encryption:
      enabled: true
      type: wireguard
    externalIPs:
      enabled: true
    kubeProxyReplacement: true
    operator:
      replicas: 1
    cluster:
      name: on-site
      id: 001
