# k8sServiceHost: 127.0.0.1
# k8sServicePort: 6443

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    encryption:
      enabled: true
      type: wireguard
    externalIPs:
      enabled: true
    kubeProxyReplacement: true
    operator:
      replicas: 1
    gatewayAPI:
      enabled: true
      gatewayClass:
        create: "true"
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true