apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    namespace: argocd
    version: 8.2.7
    valuesFile: values.yaml

# configMapGenerator:
#   - name: argocd
#     files:
#       - argocd.properties
