apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/global-cloudwork/kubernetes.git
        revision: 'main'
        files: 
          - path: applications/data/*/kustomization.yaml
          - path: applications/tenant/*/kustomization.yaml
          - path: applications/edge/*/kustomization.yaml
  template:
    metadata:
      name: {{ .path.basename }}
      labels:
        app.kubernetes.io/managed-by: argocd
    spec:
      project: {{index .path.segments 1}}
      source:
        repoURL: 'https://github.com/global-cloudwork/kubernetes.git'
        targetRevision: 'main'
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: {{ .path.basename }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: admin
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/global-cloudwork/kubernetes.git
        revision: 'main'
        directories:
          - path: environments/base/*
  template:
    metadata:
      name: '{{ .path.basename }}'
      labels:
        app.kubernetes.io/managed-by: argocd
    spec:
      project: default
      source:
        repoURL: 'https://github.com/global-cloudwork/kubernetes.git'
        targetRevision: 'main'
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true