# Secrets
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/app-project.crd.yaml
  - resources/application.crd.yaml
  - resources/application-set.crd.yaml

patches:
  - target:
      group: ""
      version: v1
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
    path: resources/argocd-patch.yaml