apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: gce-cloud-router-peering
spec:
  # Selector targets all nodes where BGP peering should occur
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  virtualRouters:
    - localASN: 64512 # Cilium's Local ASN
      serviceSelector:
        # Ensures only LoadBalancer services get advertised by this router instance
        matchExpressions:
          - {key: networking.cilium.io/service-advertisement, operator: Exists}
      neighbors:
        # The internal BGP interface IP address of the GCE Cloud Router 
        - peerAddress: '10.10.1.1/32' # Placeholder for GCE Router interface IP
          peerASN: 64512 # Peer ASN matches Local ASN for iBGP-like configuration