apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: gateway-api-allow-eastwest
  namespace: gateway-system
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: envoy-gateway
  ingress:
    - fromEntities:
        - cluster  # allow all pods within cluster
      toPorts:
        - ports:
            - port: "4244"
              protocol: TCP
            - port: "9963"
              protocol: TCP
            - port: "9964"
              protocol: TCP