apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: gateway
  annotations:
    cert-manager.io/cluster-issuer: cluster-issuer
spec:
  gatewayClassName: cilium
  listeners:
    - hostname: "*.promotesudbury.ca"
      name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All