apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - applications/core/argocd
  - applications/core/cilium/helm-chart-config.yaml
  - kubernetes/connection/gateway.k8s.yaml
  - kubernetes/connection/http-route.k8s.yaml

# configMapGenerator:
#   - name: argocd
#     files:
#       - argocd.properties
