apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---
apiVersion: v1
kind: Namespace
metadata:
  name: authentik

---
# Namespaces for core applications managed by hydrators
apiVersion: v1
kind: Namespace
metadata:
  name: traefik

---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---
apiVersion: v1
kind: Namespace
metadata:
  name: n8n

---
apiVersion: v1
kind: Namespace
metadata:
  name: neo4j

---
apiVersion: v1
kind: Namespace
metadata:
  name: homepage

---
apiVersion: v1
kind: Namespace
metadata:
  name: core

---
apiVersion: v1
kind: Namespace
metadata:
  name: data

---
apiVersion: v1
kind: Namespace
metadata:
  name: edge

---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant

---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway
