apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gateway
  namespace: gateway
  annotations:
    cert-manager.io/cluster-issuer: cluster-issuer
spec:
  gatewayClassName: cilium
  listeners:
    - hostname: "*.promotesudbury.ca"
      name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - hostname: "*.promotesudbury.ca"
      name: https-link
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
        - name: gateway-certificate #Automaticaly Created
      allowedRoutes:
        namespaces:
          from: All
    - name: udp-link
      port: 3478
      protocol: UDP
      allowedRoutes:
        namespaces:
          from: All