# HTTP Redirection Route
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-rke2
  namespace: gateway
  labels:
    app.kubernetes.io/name: rke2
spec:
  parentRefs:
  - name: gateway
    namespace: gateway
    sectionName: http
  hostnames:
  - "*.promotesudbury.ca"
  rules:
  - backendRefs:
    - name: rke2
      port: 8080
---

# # HTTP Redirection Route
# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: HTTPRoute
# metadata:
#   name: http-redirect
#   namespace: gateway
# spec:
#   parentRefs:
#   - name: gateway
#     namespace: gateway
#     sectionName: http
#   hostnames:
#   - "*.promotesudbury.ca"
#   rules:
#   - filters:
#     - type: RequestRedirect
#       requestRedirect:
#         scheme: https
#         statusCode: 301
# ---
# # ArgoCD UI
# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: HTTPRoute
# metadata:
#   name: argocd-http-route
#   namespace: gateway
# spec:
#   parentRefs:
#   - name: gateway
#     namespace: gateway
#     sectionName: https
#   hostnames:
#   - "argo.promotesudbury.ca"
#   rules:
#   - backendRefs:
#     - name: argocd-server
#       port: 30080
---
# # n8n HTTPRoute
# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: HTTPRoute
# metadata:
#   name: n8n-route
#   namespace: n8n
# spec:
#   parentRefs:
#   - name: main-gateway
#     namespace: gateway-system
#     sectionName: https
#   hostnames:
#   - "n8n.yourdomain.com"
#   rules:
#   - matches:
#     - path:
#         type: PathPrefix
#         value: /
#     backendRefs:
#     - name: n8n-service
#       port: 5678
#       weight: 100
#   - matches:
#     - path:
#         type: PathPrefix
#         value: /webhook
#     backendRefs:
#     - name: n8n-service
#       port: 5678
#       weight: 100
#   - matches:
#     - path:
#         type: PathPrefix
#         value: /rest
#     backendRefs:
#     - name: n8n-service
#       port: 5678
#       weight: 100
# ---
# # Tailscale/Headscale HTTPRoute
# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: HTTPRoute
# metadata:
#   name: tailscale-route
#   namespace: tailscale
# spec:
#   parentRefs:
#   - name: main-gateway
#     namespace: gateway-system
#     sectionName: https
#   hostnames:
#   - "tailscale.yourdomain.com"
#   rules:
#   - matches:
#     - path:
#         type: PathPrefix
#         value: /
#     backendRefs:
#     - name: headscale-service
#       port: 8080
#       weight: 100
# ---
# # UDP Route for Tailscale DERP
# apiVersion: gateway.networking.k8s.io/v1alpha2
# kind: UDPRoute
# metadata:
#   name: tailscale-derp
#   namespace: tailscale
# spec:
#   parentRefs:
#   - name: main-gateway
#     namespace: gateway-system
#     sectionName: tailscale-derp
#   rules:
#   - backendRefs:
#     - name: headscale-service
#       port: 3478