apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/managed-by: argo-cd

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: my-kube-prometheus-stack
    namespace: argocd
    version: 75.17.1

configMapGenerator:
  - name: kube-prometheus-stack
    files:
      - kube-prometheus-stack.properties