apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/global-cloudwork/kubernetes
    targetRevision: main
    path: components/base
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
