key:
  components:
    - name: actualbudget
      chart: actualbudget
      version: "1.8.1"
      releaseName: actualbudget
      repoURL: "https://community-charts.github.io/helm-charts"
      namespace: actualbudget
    - name: argocd
      chart: argocd
      version: "8.2.7"
      releaseName: argocd
      repoURL: "https://argoproj.github.io/argo-helm"
      namespace: argocd