apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
helmCharts:
  - name: wireguard
    repo: https://charts.pascaliske.dev
    namespace: wireguard
    version: 0.1.0
    releaseName: wireguard
