apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    namespace: traefik
    version: 37.1.0
    releaseName: traefik
    valuesInline:
      gateway:
        enabled: true

      providers:
        kubernetesGateway:
          enabled: true

      service:
        type: NodePort

        spec:
          externalTrafficPolicy: Local

        ports:
          web:
            nodePort: 30080

          websecure:
            nodePort: 30443