apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-deployment
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/global-cloudwork/kubernetes'
        revision: 'main'
        files:
          - path: 'components/base/core/**/*.yaml'  
  template:
    metadata:
      name: '{{path.basename}}-{{path.filename}}' 
    spec:
      project: default
      source:
        repoURL: 'https://github.com/global-cloudwork/kubernetes'
        targetRevision: 'main'
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true