apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/managed-by: argo-cd

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: my-cert-manager
    namespace: argocd
    version: 1.18.2

configMapGenerator:
  - name: cert-manager
    files:
      - cert-manager.properties