apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: n8n
    repo: https://community-charts.github.io/helm-charts
    namespace: argocd
    version: 1.14.3
    releaseName: my-n8n