apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: n8n
    repo: oci://8gears.container-registry.com/library/n8n
    releaseName: n8n
    namespace: argocd
    version: 1.0.10