apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
    operator:
      replicas: 1
    gatewayAPI:
      enabled: true
    encryption:
      enabled: true
      type: wireguard
    l7Proxy:
      enabled: true
    bpf:
      lbExternalClusterIP:
        enabled: true
    ipam:
      mode: ClusterPool
      clusterPool:
        ipv4:
          enabled: true
          cidr:35.209.166.0/24
    loadBalancer:
      l2announcement:
        enabled: true
        interface: eth0