apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443
    operator:
      replicas: 1
    encryption:
      enabled: true
      type: wireguard
    gatewayAPI:
      enabled: true
      hostNetwork:
        enabled: true
    envoy:
      securityContext:
        capabilities:
          keepCapNetBindService: true
    securityContext:
      capabilities:
        ciliumAgent:
        - NET_BIND_SERVICE