apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: ${INTERNAL_IP}
    k8sServicePort: 6443
    operator:
      replicas: 1
    encryption:
      enabled: true
      type: wireguard
    gatewayAPI:
      enabled: true
      hostNetwork:
        enabled: true