apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - application.yaml
  - secret.yaml
  - https://raw.githubusercontent.com/global-cloudwork/kubernetes/main/kubernetes/application-set.yaml


helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    namespace: argocd
    version: 9.1.0
    releaseName: argocd
    includeCRDs: true

    valuesInline:
      configs:
        params:
          server.insecure: "true"

      server:
        service:
          type: NodePort
          nodePortHttp: 30080
          nodePortHttps: 30443