apiVersion: promoter.argoproj.io/v1alpha1
kind: DependentsSuccessfulCommitStatus
metadata:
  name: traefik
  namespace: promoter-system
spec:
  key: dependents-successful
  promotionStrategyRef:
    name: traefik
