# write-kubeconfig: /home/couch/.kube/config
write-kubeconfig-mode: 0644
node-name: "local"
tls-san:
  - "127.0.0.1"
  - "localhost"
  - "argocd.localhost"
  - "192.168.4.26"
disable-kube-proxy: true
etcd-expose-metrics: false
disable:
  - rke2-ingress-nginx
cni: none
node-ip: "192.168.4.26"