apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-manifests
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/global-cloudwork/kubernetes'
        revision: 'main' 
        files:
          - path: 'kubernetes/base/applications/*.yaml'
  template:
    metadata:
      name: '{{path.basename | splitList "." | first}}' 
    spec:
      project: default
      source:
        repoURL: 'https://github.com/global-cloudwork/kubernetes'
        targetRevision: 'main'
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: argocd  
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gateway-manifests
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/global-cloudwork/kubernetes'
        revision: 'main' 
        files:
          - path: 'kubernetes/base/gateway/*.yaml'
  template:
    metadata:
      name: '{{path.basename | splitList "." | first}}' 
    spec:
      project: default
      source:
        repoURL: 'https://github.com/global-cloudwork/kubernetes'
        targetRevision: 'main'
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: argocd  
      syncPolicy:
        automated:
          prune: true
          selfHeal: true