apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-deployment
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: 
  - "missingkey=error"
  generators:
    - matrix:
        generators:
        - git:
            repoURL: https://github.com/global-cloudwork/kubernetes.git
            revision: main
            files:
            - path: applications.yaml
        - list:
            elements: []
            elementsYaml: '{{ .key.components | toJson }}'
  template:
    metadata:
      name: '{{ .name }}'
    spec:
      project: default
      sources:
        - repoURL: '{{ .repoURL }}'
          chart: '{{ .chart }}'
          targetRevision: '{{ .version }}'
          helm:
            releaseName: '{{ .releaseName }}'
            valueFiles:
              - https://raw.githubusercontent.com/global-cloudwork/kubernetes/main/components/applications/{{ .name }}/values.yaml
          # kustomize:
          #   labels:
          #     - includeSelectors: true
          #       includeTemplates: true
          #       pairs:
          #         app.kubernetes.io/part-of: '{{ .name }}'
          #         app.kubernetes.io/managed-by: 'argocd'
          #   ignoreMissingComponents: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true