apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-role-binding
subjects:
  - kind: ServiceAccount
    name: argocd-service-account
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io

