apiVersion: v1
kind: Secret
metadata:
  name: cloudwork-kubernetes-repository
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
stringData:
  type: git
  name: cloudwork-kubernetes
  url: https://github.com/global-cloudwork/kubernetes.git
  targetRevision: development
---
apiVersion: v1
kind: Secret
metadata:
  name: k3s-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: k3s
  server: https://kubernetes.default.svc
  project: default
  config: |
    {
      "tlsClientConfig": {
        "insecure": true
      }
    }
