# apiVersion: "cilium.io/v2alpha1"
# kind: CiliumLoadBalancerIPPool
# metadata:
#   name: example-ip-pool
#   namespace: kube-system
# spec:
#   cidrs:
#   - cidr: "10.0.1.250/30"
#   serviceSelector:
#     matchLabels:
#       "io.kubernetes.service.namespace": "common"

# ---
# apiVersion: "cilium.io/v2alpha1"
# kind: CiliumL2AnnouncementPolicy
# metadata:
#   name: example-l2advertisement-policy
#   namespace: kube-system
# spec:
#   serviceSelector:
#     matchLabels:
#       io.cilium.gateway/owning-gateway: example
#   interfaces:
#     - ^enx+ # host interface regex
#   externalIPs: true
#   loadBalancerIPs: true

apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "ipv4-ip-pool"
  namespace: argocd
spec:
  blocks:
  - start: "10.10.20.10"
    stop: "10.10.20.20"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-announcement-policy
  namespace: argocd
spec:
  interfaces:
    - eth0
  externalIPs: true
  loadBalancerIPs: true