apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
spec:
  destinations:
    - namespace: core
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      groups:
        - platform-admins
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: data
spec:
  destinations:
    - namespace: data
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      groups:
        - platform-admins
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: edge
spec:
  destinations:
    - namespace: edge
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      groups:
        - platform-admins
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant
spec:
  destinations:
    - namespace: tenant
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      groups:
        - platform-admins
