apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  goTemplate: true 
  generators:
    - git:
        repoURL: https://github.com/global-cloudwork/kubernetes.git
        revision: main
        directories:
          - path: '*' # If your apps live in a subfolder, use 'apps/*' instead
  template:
    metadata:
      name: '{{ .path.basename }}' # Fixed string mapping
    spec:
      project: default
      source:
        repoURL: https://github.com/global-cloudwork/kubernetes.git
        targetRevision: main
        path: '{{ .path.path }}' # Fixed string mapping
        kustomize:
          buildOptions: "--enable-helm"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .path.basename }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true