apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: argocd

spec:
  goTemplate: true

  generators:
    - git:
        repoURL: https://github.com/global-cloudwork/kubernetes.git
        revision: main
        directories:
          - path: applications/*

  template:
    metadata:
      name: '{{ .path.basename }}'

    spec:
      project: default

      source:
        repoURL: https://github.com/global-cloudwork/kubernetes.git
        targetRevision: main
        path: '{{ .path.path }}'

        kustomize:
          buildOptions: >-
            --enable-helm
            --load-restrictor LoadRestrictionsNone

      destination:
        server: https://kubernetes.default.svc

        # Uses the application folder name:
        # applications/keycloak -> namespace keycloak
        # applications/n8n -> namespace n8n
        namespace: '{{ .path.basename }}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true

      revisionHistoryLimit: 3