template:
  metadata:
    name: '{{ base (index .path "path") }}'

  spec:
    project: default

    source:
      repoURL: https://github.com/global-cloudwork/kubernetes.git
      targetRevision: main
      path: '{{ index .path "path" }}'
      kustomize:
        buildOptions: "--enable-helm"

    destination:
      server: https://kubernetes.default.svc
      namespace: '{{ base (index .path "path") }}'

    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
