apiVersion: promoter.argoproj.io/v1alpha1
kind: DependentsSuccessfulCommitStatus
metadata:
  name: traefik
  namespace: promoter-system
spec:
  key: dependents-successful
  promotionStrategyRef:
    name: traefik
---
apiVersion: promoter.argoproj.io/v1alpha1
kind: DependentsSuccessfulCommitStatus
metadata:
  name: argocd
  namespace: promoter-system
spec:
  key: dependents-successful
  promotionStrategyRef:
    name: argocd
---
apiVersion: promoter.argoproj.io/v1alpha1
kind: DependentsSuccessfulCommitStatus
metadata:
  name: cert-manager
  namespace: promoter-system
spec:
  key: dependents-successful
  promotionStrategyRef:
    name: cert-manager
---
apiVersion: promoter.argoproj.io/v1alpha1
kind: DependentsSuccessfulCommitStatus
metadata:
  name: authentik
  namespace: promoter-system
spec:
  key: dependents-successful
  promotionStrategyRef:
    name: authentik
---
apiVersion: promoter.argoproj.io/v1alpha1
kind: DependentsSuccessfulCommitStatus
metadata:
  name: n8n
  namespace: promoter-system
spec:
  key: dependents-successful
  promotionStrategyRef:
    name: n8n
---
apiVersion: promoter.argoproj.io/v1alpha1
kind: DependentsSuccessfulCommitStatus
metadata:
  name: neo4j
  namespace: promoter-system
spec:
  key: dependents-successful
  promotionStrategyRef:
    name: neo4j
---
apiVersion: promoter.argoproj.io/v1alpha1
kind: DependentsSuccessfulCommitStatus
metadata:
  name: homepage
  namespace: promoter-system
spec:
  key: dependents-successful
  promotionStrategyRef:
    name: homepage
