apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/argoproj-labs/gitops-promoter/releases/download/v0.40.1/install-with-dashboard-cert-manager.yaml
  - application-set.yaml
  - app-project.yaml
  - argocd-commit-status.yaml
  - dependents-successful-commit-status.yaml
  - gateway-class.yaml
  - gateway.yaml
  - git-repository.yaml
  - ingress.yaml
  - promotion-strategy.yaml
  - scm-provider.yaml
