apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: founder
  namespace: argocd
spec:
  description: Core deployment project
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceBlacklist: []
