
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-message
  namespace: argocd
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome</title>
    </head>
    <body>
        <h1>Hello from IPv4!</h1>
    </body>
    </html>
