apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: keycloak
    repo: https://charts.bitnami.com/bitnami
    releaseName: keycloak
    namespace: keycloak
    version: 26.3.3
    valuesFile: values.yaml
