apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: environment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/global-cloudwork/kubernetes.git
    targetRevision: main
    path: base/admin
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true