apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces-and-projects
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/global-cloudwork/kubernetes.git
    targetRevision: main
    path: base/admin
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/global-cloudwork/kubernetes.git
    targetRevision: main
    path: enviroment/development
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true